### ISSUE TITLE
documentation can be simplifiled

### ISSUE THREAD

**Issue by stephens999** [youngseok-kim/mixSQP#2]
the docs don't need to specify the default values when they are specified in the function header (and including them risks having conflicting information). For example your value for eps
is different in the docs than in the code! best not to say in the docs as the code is necessarily correct!

And don't say that things are assumed to sum to 1, if actually you normalize them to sum to 1.
Just say they are normalized to sum to 1.

**Comment by pcarbo** [comment]
@stephens999 We have filled out the roxygen2 docs for all the exported functions; feel free to re-open, or create a new issue, if you notice other problems with the package documentation.
